### ISSUE TITLE
Swift 2.0 compatibility

### ISSUE THREAD

**Issue by benjamincombes** [lucasihlstrom/CleanNotification#3]
Thanks for your great work :) ! However, the project does not compile with Xcode 7 due to Swift 2.0 changes.

**Comment by lucasihlstrom** [comment]
Ah, yeah! I'll get on that this weekend :)

**Comment by benjamincombes** [comment]
Thanks a lot, let me know if I can do anything to help!

**Comment by lucasihlstrom** [comment]
Added Swift 2.0 support in version 1.3!

**Comment by benjamincombes** [comment]
Great, thanks :) !
